name: "Setup PHP"

description: "Setup PHP executable and extensions"

inputs:
  php-version:
    description: "PHP Version to install"
    required: false
    default: '8.3'
  php-extensions:
    description: "PHP Extension needed"
    required: false
    default: 'mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql'
  composer-flags:
    description: "Composer flag for install"
    required: false
    default: '--no-progress --prefer-dist --optimize-autoloader'

runs:
  using: "composite"
  steps:
    # Docs: https://github.com/shivammathur/setup-php
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.php-extensions }}
        coverage: xdebug

    - name: Get composer cache directory
      id: composer-cache
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        # Use composer.json for key, if composer.lock is not committed.
        # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      shell: bash
      run: composer install ${{ inputs.composer-flags }}
