# GitHub Action for Symfony with MySQL
name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: ["master"]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.31
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: symfony
          MYSQL_DATABASE: symfony_test
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:6
        ports:
          - 6379/tcp
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: ./.github/actions/setup-php

      - name: Check format
        run: composer format-check

      - name: Static Analysis
        run: composer psalm

      - name: Run Migrations
        run: php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
        env:
          APP_ENV: test
          KERNEL_CLASS: 'DeadlockHub\Kernel'
          DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony?serverVersion=8.0.31&charset=utf8mb4
          REDIS_DSN: redis://127.0.0.1:${{ job.services.redis.ports['6379'] }}

      - name: Run tests
        run: vendor/bin/phpunit --coverage-text