name: Publish Docker images

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-ansi --no-dev --no-interaction --no-progress --optimize-autoloader --ignore-platform-reqs --no-scripts

      - name: Create local artifact
        run: |
          echo "Github Ref: ${{ github.ref_name }}"
          mkdir ./docker/artifact
          cp -R ./bin ./docker/artifact/bin
          cp -R ./config ./docker/artifact/config
          cp -R ./migrations ./docker/artifact/migrations
          cp -R ./public ./docker/artifact/public
          cp -R ./src ./docker/artifact/src
          cp -R ./vendor ./docker/artifact/vendor
          cp -R ./var ./docker/artifact/var
          cp .env ./docker/artifact/.env
          cp composer.json ./docker/artifact/composer.json
          cp composer.lock ./docker/artifact/composer.lock
          cp symfony.lock ./docker/artifact/symfony.lock

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push web image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          file: ./docker/Dockerfile-web
          target: web
          push: true
          tags: mattiabasone/deadlockhub-hub:web-latest, mattiabasone/deadlock-hub:web-${{ github.ref_name }}
          cache-from: type=registry,ref=mattiabasone/deadlock-hub:web-latest
          cache-to: type=inline

      - name: Build and push worker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          file: ./docker/Dockerfile-worker
          target: worker
          push: true
          tags: mattiabasone/deadlockhub-hub:worker-latest, mattiabasone/deadlock-hub:worker-${{ github.ref_name }}
          cache-from: type=registry,ref=mattiabasone/deadlock-hub:worker-latest
          cache-to: type=inline